"""Notebook export/import — standalone notebook.py read/write."""

from __future__ import annotations

from pathlib import Path

from maribox.notebook.cell import Cell, CellId


def export_notebook(cells: list[Cell], path: Path) -> None:
    """Write a standalone marimo notebook.py file.

    Generates proper marimo cell decorators so the file can be run with
    `marimo run notebook.py`.
    """
    lines: list[str] = [
        '"""maribox notebook — generated by maribox."""',
        "",
        "import marimo as mo",
        "",
    ]

    for cell in cells:
        name = cell.name or cell.id
        lines.append("@app.cell")
        lines.append(f"def {name}():")
        for code_line in cell.code.splitlines():
            lines.append(f"    {code_line}")
        lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def import_notebook(path: Path) -> list[Cell]:
    """Parse an existing marimo notebook file into Cell objects.

    Extracts cells marked with the @app.cell decorator.
    """
    if not path.is_file():
        return []

    source = path.read_text(encoding="utf-8")
    cells: list[Cell] = []
    cell_id_counter = 0

    lines = source.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.strip().startswith("@app.cell"):
            # Parse the function name
            i += 1
            if i < len(lines):
                func_line = lines[i]
                name = func_line.strip()
                name = name[4:name.index("(")] if name.startswith("def ") and "(" in name else None

            # Collect indented body
            code_lines: list[str] = []
            i += 1
            while i < len(lines):
                body_line = lines[i]
                if body_line and not body_line[0].isspace() and body_line.strip():
                    break
                if body_line.strip():
                    # Dedent by 4 spaces
                    if body_line.startswith("    "):
                        code_lines.append(body_line[4:])
                    else:
                        code_lines.append(body_line.strip())
                i += 1

            cell_id_counter += 1
            cells.append(Cell(
                id=CellId(f"cell_{cell_id_counter}"),
                code="\n".join(code_lines),
                name=name,
            ))
        else:
            i += 1

    return cells
